name: Run Tests

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Install tools
        run: |
          sudo apt install python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          cd src
          python3 -m pytest